[package]
name = "web-socket"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = { version = "0.26.2" }
log = "0.4"
env_logger = "0.11.6"
futures-util = "0.3.31"
uuid = { version = "1.14.0", features = ["v4"] }
